server:
  port: 8083

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  openapi:
    security-header: Authorization
    service-prefix: /soybean-auth
    title: auth
    version: 1.0.0

spring:
  application:
    name: soybean-auth
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.addr@ # nacos地址
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: @nacos.namespace@
        group: DEFAULT_GROUP
      config:
        namespace: @nacos.namespace@
        group: DEFAULT_GROUP
  config:
    import:
      - optional:nacos:soybean.common.yaml
      - optional:nacos:soybean.jdbc.yaml
      - optional:nacos:soybean.sa-token.yaml