server:
  port: 9090

spring:
  application:
    name: soybean-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
      username: nacos
      password: nacos
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      username: default
      password: redis123
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
    gateway:
      routes: # 路由配置
        - id: soybean-auth
          uri: lb://soybean-auth
          predicates: # 断言
            - Path=/auth/**
        - id: soybean-user
          uri: lb://soybean-user
          predicates: # 断言
            - Path=/user/**
        - id: soybean-upms
          uri: lb://soybean-upms
          predicates: # 断言
            - Path=/sys/**

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从header中读取token
  is-read-header: true
  # token前缀
  token-prefix: Bearer

# 放行URL配置
security:
  permit-all:
    urls:
      - /user/admin
      - /auth/**
