server:
  port: 9090

spring:
  application:
    name: soybean-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
      username: nacos
      password: nacos
    gateway:
      routes: # 路由配置
        - id: soybean-user
          uri: lb://soybean-user
          predicates: # 断言
            - Path=/user/**