soybean:
  nacos-host: 192.168.22.13
  nacos-port: 8848
  openapi:
    security-header: Authorization
    service-prefix: /soybean-upms
    title: UPMS
    version: 1.0.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false

server:
  port: 8081

spring:
  application:
    name: soybean-upms
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.addr@ # nacos地址
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: @nacos.namespace@
        group: DEFAULT_GROUP
      config:
        namespace: @nacos.namespace@
        group: DEFAULT_GROUP
  config:
    import:
      - optional:nacos:soybean.common.yaml
      - optional:nacos:soybean.jdbc.yaml
      - optional:nacos:soybean.sa-token.yaml
      - optional:nacos:soybean.seata.yaml